[workspace]
members = ["kaka-nest"]
resolver = "2"

[workspace.dependencies]
# Highlighting
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.33"
serde_json = "1.0.143"

[profile.release]
debug = "full"
