[workspace]
members = ["kaka-nest"]
resolver = "2"
metadata.crane.name = "kaka-nest-workspace"

[workspace.dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.33"
serde_json = "1.0.143"

[profile.release]
debug = "full"
