[package]
name = "kaka-nest"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
pulldown-cmark = "0.13.0"
tokio = { version = "1.47.1", features = ["full"] }
tracing-subscriber = "0.3.19"
