[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
linker = "clang"

[build]
rustflags = ["-Z", "threads=12"]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"
